### ISSUE TITLE
No validation config for train.yaml

### ISSUE THREAD

**Issue by smallfade** [AllenInstitute/aics-ml-segmentation#2]
It's better to provide a sample config file for both the training and prediction. Otherwise, users have to look into the source code to figure out what is missing from the configuration.
Here is what I added in the train.yaml to make it work:

```
validation:
  leaveout: [1]
  metric: 'MeanIoU'
  OutputCh: [1]
  validate_every_n_epoch: 40
```
